install:
    - ps: Set-Service wuauserv -StartupType "Automatic"; Start-Service wuauserv # weird magic for 'cinst php'
    - cinst php --version 7.3.0
    - echo extension=C:\tools\php73\ext\php_openssl.dll >> C:\tools\php73\php.ini
    - echo extension=C:\tools\php73\ext\php_mbstring.dll >> C:\tools\php73\php.ini
    - echo extension=C:\tools\php73\ext\php_curl.dll >> C:\tools\php73\php.ini
    - echo zend_extension=C:\tools\php73\ext\php_opcache.dll >> C:\tools\php73\php.ini
    - set PATH=C:\tools\php73;%PATH%
    - appveyor DownloadFile https://getcomposer.org/download/1.8.6/composer.phar
    - php composer.phar i --working-dir=php-bin
    - php composer.phar i --working-dir=php-project-for-tests --no-interaction
    - php composer.phar i --working-dir=symfony-2.8-project --no-interaction
    - php composer.phar i --working-dir=symfony-3.4-project --no-interaction
    - php composer.phar i --working-dir=symfony-4.2-project --no-interaction
    - ps: Install-Product node 8.9.0
    - npm i

build: off

test_script:
    - npm test
