dist: xenial

language: node_js

node_js:
    - "10.2"

install:
    - wget https://getcomposer.org/download/1.8.6/composer.phar
    - php composer.phar install --working-dir php-bin
    - php composer.phar install --working-dir symfony-3.4-project
    - php composer.phar install --working-dir symfony-4.2-project
    - npm i

after_script:
    - npm run coverage-lcov
    - npm install --save-dev coveralls@3.0.4
    - coveralls < ./coverage/lcov.info
