dist: xenial

language: node_js

node_js:
    - "10.2"

install:
    - wget https://getcomposer.org/download/1.8.6/composer.phar
    - php composer.phar install --working-dir php-bin
    - php composer.phar install --working-dir symfony-project-for-tests
    - npm i
